import { registerEntity } from "@/admin/lib/entity-registry";
import { L } from "@/i18n/admin-lang";

registerEntity({
  key: "article",
  label: L("مقال", "Article"),
  labelPlural: L("المقالات", "Articles"),
  table: "insight_articles",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Newspaper",
  previewPathTemplate: "/insights/{category_slug}/{slug}",
  fields: [
    { key: "slug", label: L("المعرّف (Slug)", "Slug"), kind: "slug", required: true },
    { key: "title_ar", label: L("العنوان (عربي)", "Title (AR)"), kind: "text", required: true, localized: true },
    { key: "title_en", label: L("العنوان (إنجليزي)", "Title (EN)"), kind: "text", required: true, localized: true },
    { key: "category_id", label: L("التصنيف", "Category"), kind: "relation", relationTo: "insight_categories" },
    { key: "excerpt_ar", label: L("المقتطف (عربي)", "Excerpt (AR)"), kind: "textarea", localized: true },
    { key: "excerpt_en", label: L("المقتطف (إنجليزي)", "Excerpt (EN)"), kind: "textarea", localized: true },
    { key: "content_ar", label: L("المحتوى (عربي)", "Content (AR)"), kind: "richtext", localized: true },
    { key: "content_en", label: L("المحتوى (إنجليزي)", "Content (EN)"), kind: "richtext", localized: true },
    { key: "cover_url", label: L("رابط الغلاف", "Cover URL"), kind: "text" },
    { key: "featured_image_url", label: L("الصورة المميّزة", "Featured image URL"), kind: "text" },
    { key: "author_name", label: L("اسم الكاتب", "Author name"), kind: "text" },
    { key: "author_avatar_url", label: L("صورة الكاتب", "Author avatar URL"), kind: "text" },
    { key: "reading_minutes", label: L("دقائق القراءة", "Reading minutes"), kind: "number" },
    { key: "tags", label: L("الوسوم", "Tags"), kind: "multiselect" },
    { key: "keywords", label: L("الكلمات المفتاحية", "Keywords"), kind: "multiselect" },
    { key: "faq", label: L("الأسئلة الشائعة", "FAQ"), kind: "json" },
    { key: "gallery", label: L("معرض الصور", "Gallery"), kind: "json" },
    { key: "related_article_ids", label: L("مقالات ذات صلة", "Related article IDs"), kind: "multiselect" },
    { key: "featured", label: L("مميّز", "Featured"), kind: "boolean" },
    { key: "scheduled_at", label: L("موعد الجدولة", "Scheduled at"), kind: "date" },
    { key: "seo_title_ar", label: L("عنوان SEO (عربي)", "SEO title (AR)"), kind: "text", localized: true },
    { key: "seo_title_en", label: L("عنوان SEO (إنجليزي)", "SEO title (EN)"), kind: "text", localized: true },
    { key: "seo_description_ar", label: L("وصف SEO (عربي)", "SEO description (AR)"), kind: "textarea", localized: true },
    { key: "seo_description_en", label: L("وصف SEO (إنجليزي)", "SEO description (EN)"), kind: "textarea", localized: true },
  ],
  listColumns: [
    { key: "title_en", label: L("العنوان", "Title"), sortable: true },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "workflow_state", label: L("الحالة", "State"), render: "workflow" },
    { key: "updated_at", label: L("آخر تحديث", "Updated"), render: "date", sortable: true },
  ],
});
