import { registerEntity } from "@/admin/lib/entity-registry";

registerEntity({
  key: "article",
  label: "Article",
  labelPlural: "Articles",
  table: "insight_articles",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Newspaper",
  previewPathTemplate: "/insights/{category_slug}/{slug}",
  fields: [
    { key: "slug", label: "Slug", kind: "slug", required: true },
    { key: "title_ar", label: "Title (AR)", kind: "text", required: true, localized: true },
    { key: "title_en", label: "Title (EN)", kind: "text", required: true, localized: true },
    { key: "category_id", label: "Category", kind: "relation", relationTo: "insight_categories" },
    { key: "excerpt_ar", label: "Excerpt (AR)", kind: "textarea", localized: true },
    { key: "excerpt_en", label: "Excerpt (EN)", kind: "textarea", localized: true },
    { key: "content_ar", label: "Content (AR)", kind: "richtext", localized: true },
    { key: "content_en", label: "Content (EN)", kind: "richtext", localized: true },
    { key: "cover_url", label: "Cover URL", kind: "text" },
    { key: "featured_image_url", label: "Featured image URL", kind: "text" },
    { key: "author_name", label: "Author name", kind: "text" },
    { key: "author_avatar_url", label: "Author avatar URL", kind: "text" },
    { key: "reading_minutes", label: "Reading minutes", kind: "number" },
    { key: "tags", label: "Tags", kind: "multiselect" },
    { key: "keywords", label: "Keywords", kind: "multiselect" },
    { key: "faq", label: "FAQ", kind: "json" },
    { key: "gallery", label: "Gallery", kind: "json" },
    { key: "related_article_ids", label: "Related article IDs", kind: "multiselect" },
    { key: "featured", label: "Featured", kind: "boolean" },
    { key: "scheduled_at", label: "Scheduled at", kind: "date" },
    { key: "seo_title_ar", label: "SEO title (AR)", kind: "text", localized: true },
    { key: "seo_title_en", label: "SEO title (EN)", kind: "text", localized: true },
    { key: "seo_description_ar", label: "SEO description (AR)", kind: "textarea", localized: true },
    { key: "seo_description_en", label: "SEO description (EN)", kind: "textarea", localized: true },
  ],
  listColumns: [
    { key: "title_en", label: "Title", sortable: true },
    { key: "slug", label: "Slug" },
    { key: "workflow_state", label: "State", render: "workflow" },
    { key: "updated_at", label: "Updated", render: "date", sortable: true },
  ],
});
