import { registerEntity } from "@/admin/lib/entity-registry";
import { L } from "@/i18n/admin-lang";

registerEntity({
  key: "project",
  label: L("مشروع", "Project"),
  labelPlural: L("المشاريع", "Projects"),
  table: "portfolio_projects",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Briefcase",
  previewPathTemplate: "/projects/{category_slug}/{slug}",
  fields: [
    { key: "slug", label: L("المعرّف (Slug)", "Slug"), kind: "slug", required: true },
    { key: "name_ar", label: L("الاسم (عربي)", "Name (AR)"), kind: "text", required: true, localized: true },
    { key: "name_en", label: L("الاسم (إنجليزي)", "Name (EN)"), kind: "text", required: true, localized: true },
    { key: "client", label: L("العميل", "Client"), kind: "text" },
    { key: "industry", label: L("الصناعة", "Industry"), kind: "text" },
    { key: "category_slug", label: L("معرّف التصنيف", "Category slug"), kind: "text" },
    { key: "short_description_ar", label: L("وصف مختصر (عربي)", "Short description (AR)"), kind: "textarea", localized: true },
    { key: "short_description_en", label: L("وصف مختصر (إنجليزي)", "Short description (EN)"), kind: "textarea", localized: true },
    { key: "challenge_ar", label: L("التحدي (عربي)", "Challenge (AR)"), kind: "richtext", localized: true },
    { key: "challenge_en", label: L("التحدي (إنجليزي)", "Challenge (EN)"), kind: "richtext", localized: true },
    { key: "solution_ar", label: L("الحل (عربي)", "Solution (AR)"), kind: "richtext", localized: true },
    { key: "solution_en", label: L("الحل (إنجليزي)", "Solution (EN)"), kind: "richtext", localized: true },
    { key: "results_ar", label: L("النتائج (عربي)", "Results (AR)"), kind: "richtext", localized: true },
    { key: "results_en", label: L("النتائج (إنجليزي)", "Results (EN)"), kind: "richtext", localized: true },
    { key: "services_used", label: L("الخدمات المستخدمة", "Services used"), kind: "multiselect" },
    { key: "gallery", label: L("معرض الصور", "Gallery"), kind: "json" },
    { key: "featured", label: L("مميّز", "Featured"), kind: "boolean" },
    { key: "sort_order", label: L("ترتيب العرض", "Sort order"), kind: "number" },
    { key: "project_url", label: L("رابط المشروع", "Project URL"), kind: "text" },
    { key: "seo_title_ar", label: L("عنوان SEO (عربي)", "SEO title (AR)"), kind: "text", localized: true },
    { key: "seo_title_en", label: L("عنوان SEO (إنجليزي)", "SEO title (EN)"), kind: "text", localized: true },
    { key: "seo_description_ar", label: L("وصف SEO (عربي)", "SEO description (AR)"), kind: "textarea", localized: true },
    { key: "seo_description_en", label: L("وصف SEO (إنجليزي)", "SEO description (EN)"), kind: "textarea", localized: true },
    { key: "seo_keywords", label: L("كلمات SEO المفتاحية", "SEO keywords"), kind: "multiselect" },
    { key: "og_image_url", label: L("رابط صورة OG", "OG image URL"), kind: "text" },
  ],
  listColumns: [
    { key: "name_en", label: L("الاسم", "Name"), sortable: true },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "workflow_state", label: L("الحالة", "State"), render: "workflow" },
    { key: "updated_at", label: L("آخر تحديث", "Updated"), render: "date", sortable: true },
  ],
});
