import { registerEntity } from "@/admin/lib/entity-registry";
import { L } from "@/i18n/admin-lang";

registerEntity({
  key: "project",
  label: L("مشروع", "Project"),
  labelPlural: L("المشاريع", "Projects"),
  table: "portfolio_projects",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Briefcase",
  previewPathTemplate: "/projects/{category_slug}/{slug}",
  fields: [
    { key: "slug", label: L("المعرّف (Slug)", "Slug"), kind: "slug", required: true , group: L("الأساسيات", "Basics") },
    { key: "name_ar", label: L("الاسم (عربي)", "Name (AR)"), kind: "text", required: true, localized: true , group: L("الأساسيات", "Basics") },
    { key: "name_en", label: L("الاسم (إنجليزي)", "Name (EN)"), kind: "text", required: true, localized: true , group: L("الأساسيات", "Basics") },
    { key: "client", label: L("العميل", "Client"), kind: "text" , group: L("الأساسيات", "Basics") },
    { key: "industry", label: L("الصناعة", "Industry"), kind: "text" , group: L("الأساسيات", "Basics") },
    {
      key: "category_slug",
      label: L("التصنيف", "Category"),
      kind: "select",
      required: true,
      optionsSource: {
        table: "project_categories",
        valueColumn: "slug",
        labelArColumn: "name_ar",
        labelEnColumn: "name_en",
        orderBy: "sort_order",
      },
      helpText: L("يحدّد الصفحة التي يظهر بها المشروع.", "Determines which category page the project appears in."),
    },
    { key: "short_description_ar", label: L("وصف مختصر (عربي)", "Short description (AR)"), kind: "textarea", localized: true , group: L("المحتوى", "Content") },
    { key: "short_description_en", label: L("وصف مختصر (إنجليزي)", "Short description (EN)"), kind: "textarea", localized: true , group: L("المحتوى", "Content") },
    { key: "challenge_ar", label: L("التحدي (عربي)", "Challenge (AR)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "challenge_en", label: L("التحدي (إنجليزي)", "Challenge (EN)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "solution_ar", label: L("الحل (عربي)", "Solution (AR)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "solution_en", label: L("الحل (إنجليزي)", "Solution (EN)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "results_ar", label: L("النتائج (عربي)", "Results (AR)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "results_en", label: L("النتائج (إنجليزي)", "Results (EN)"), kind: "richtext", localized: true , group: L("المحتوى", "Content") },
    { key: "services_used", label: L("الخدمات المستخدمة", "Services used"), kind: "multiselect" , group: L("المحتوى", "Content") },
    {
      key: "thumbnail_url",
      group: L("الوسائط", "Media"),
      label: L("صورة الغلاف", "Cover image"),
      kind: "media",
      helpText: L("تظهر في قوائم المشاريع والبطاقات.", "Shown in project lists and cards."),
    },
    {
      key: "hero_image_url",
      label: L("صورة الهيرو", "Hero image"),
      kind: "media",
      helpText: L("الصورة الكبيرة أعلى صفحة المشروع.", "Large image at the top of the project page."),
    },
    {
      key: "gallery",
      label: L("صور إضافية", "Additional images"),
      kind: "gallery",
      helpText: L("معرض صور المشروع بالترتيب.", "Project gallery images, in order."),
    },

    { key: "featured", label: L("مميّز", "Featured"), kind: "boolean" , group: L("إعدادات العرض", "Display settings") },
    { key: "sort_order", label: L("ترتيب العرض", "Sort order"), kind: "number" , group: L("إعدادات العرض", "Display settings") },
    { key: "project_url", label: L("رابط المشروع", "Project URL"), kind: "text" , group: L("إعدادات العرض", "Display settings") },
    { key: "seo_title_ar", label: L("عنوان SEO (عربي)", "SEO title (AR)"), kind: "text", localized: true },
    { key: "seo_title_en", label: L("عنوان SEO (إنجليزي)", "SEO title (EN)"), kind: "text", localized: true },
    { key: "seo_description_ar", label: L("وصف SEO (عربي)", "SEO description (AR)"), kind: "textarea", localized: true },
    { key: "seo_description_en", label: L("وصف SEO (إنجليزي)", "SEO description (EN)"), kind: "textarea", localized: true },
    { key: "seo_keywords", label: L("كلمات SEO المفتاحية", "SEO keywords"), kind: "multiselect" },
    { key: "og_image_url", label: L("صورة OG", "OG image"), kind: "media" },
  ],
  listColumns: [
    { key: "name_en", label: L("الاسم", "Name"), sortable: true , group: L("الأساسيات", "Basics") },
    { key: "slug", label: L("المعرّف", "Slug") , group: L("الأساسيات", "Basics") },
    { key: "category_slug", label: L("التصنيف", "Category"), render: "badge" , group: L("الأساسيات", "Basics") },
    { key: "workflow_state", label: L("الحالة", "State"), render: "workflow" },
    { key: "updated_at", label: L("آخر تحديث", "Updated"), render: "date", sortable: true },
  ],
});
