import { registerEntity } from "@/admin/lib/entity-registry";

registerEntity({
  key: "project",
  label: "Project",
  labelPlural: "Projects",
  table: "portfolio_projects",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Briefcase",
  previewPathTemplate: "/projects/{category_slug}/{slug}",
  fields: [
    { key: "slug", label: "Slug", kind: "slug", required: true },
    { key: "name_ar", label: "Name (AR)", kind: "text", required: true, localized: true },
    { key: "name_en", label: "Name (EN)", kind: "text", required: true, localized: true },
    { key: "client", label: "Client", kind: "text" },
    { key: "industry", label: "Industry", kind: "text" },
    { key: "category_slug", label: "Category slug", kind: "text" },
    { key: "short_description_ar", label: "Short description (AR)", kind: "textarea", localized: true },
    { key: "short_description_en", label: "Short description (EN)", kind: "textarea", localized: true },
    { key: "challenge_ar", label: "Challenge (AR)", kind: "richtext", localized: true },
    { key: "challenge_en", label: "Challenge (EN)", kind: "richtext", localized: true },
    { key: "solution_ar", label: "Solution (AR)", kind: "richtext", localized: true },
    { key: "solution_en", label: "Solution (EN)", kind: "richtext", localized: true },
    { key: "results_ar", label: "Results (AR)", kind: "richtext", localized: true },
    { key: "results_en", label: "Results (EN)", kind: "richtext", localized: true },
    { key: "services_used", label: "Services used", kind: "multiselect" },
    { key: "gallery", label: "Gallery", kind: "json" },
    { key: "featured", label: "Featured", kind: "boolean" },
    { key: "sort_order", label: "Sort order", kind: "number" },
    { key: "project_url", label: "Project URL", kind: "text" },
    { key: "seo_title_ar", label: "SEO title (AR)", kind: "text", localized: true },
    { key: "seo_title_en", label: "SEO title (EN)", kind: "text", localized: true },
    { key: "seo_description_ar", label: "SEO description (AR)", kind: "textarea", localized: true },
    { key: "seo_description_en", label: "SEO description (EN)", kind: "textarea", localized: true },
    { key: "seo_keywords", label: "SEO keywords", kind: "multiselect" },
    { key: "og_image_url", label: "OG image URL", kind: "text" },
  ],
  listColumns: [
    { key: "name_en", label: "Name", sortable: true },
    { key: "slug", label: "Slug" },
    { key: "workflow_state", label: "State", render: "workflow" },
    { key: "updated_at", label: "Updated", render: "date", sortable: true },
  ],
});
