import { registerEntity } from "@/admin/lib/entity-registry";
import { L } from "@/i18n/admin-lang";

registerEntity({
  key: "service",
  label: L("خدمة", "Service"),
  labelPlural: L("الخدمات", "Services"),
  table: "services",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Sparkles",
  fields: [
    { key: "slug", label: L("المعرّف (Slug)", "Slug"), kind: "slug", required: true },
    { key: "title_ar", label: L("العنوان (عربي)", "Title (AR)"), kind: "text", required: true, localized: true },
    { key: "title_en", label: L("العنوان (إنجليزي)", "Title (EN)"), kind: "text", required: true, localized: true },
    { key: "description_ar", label: L("الوصف (عربي)", "Description (AR)"), kind: "textarea", localized: true },
    { key: "description_en", label: L("الوصف (إنجليزي)", "Description (EN)"), kind: "textarea", localized: true },
    { key: "features", label: L("المميّزات", "Features"), kind: "json", helpText: L("مصفوفة نصوص — ميزة واحدة لكل عنصر.", "Array of strings — one feature per entry.") },
    { key: "icon", label: L("الأيقونة (اسم Lucide)", "Icon (Lucide name)"), kind: "text" },
    { key: "cta_label_ar", label: L("نص الزر (عربي)", "CTA label (AR)"), kind: "text", localized: true },
    { key: "cta_label_en", label: L("نص الزر (إنجليزي)", "CTA label (EN)"), kind: "text", localized: true },
    { key: "cta_href", label: L("رابط الزر", "CTA href"), kind: "text" },
    { key: "featured", label: L("مميّز", "Featured"), kind: "boolean" },
    { key: "sort_order", label: L("ترتيب العرض", "Sort order"), kind: "number" },
    { key: "seo_title_ar", label: L("عنوان SEO (عربي)", "SEO title (AR)"), kind: "text", localized: true },
    { key: "seo_title_en", label: L("عنوان SEO (إنجليزي)", "SEO title (EN)"), kind: "text", localized: true },
    { key: "seo_description_ar", label: L("وصف SEO (عربي)", "SEO description (AR)"), kind: "textarea", localized: true },
    { key: "seo_description_en", label: L("وصف SEO (إنجليزي)", "SEO description (EN)"), kind: "textarea", localized: true },
    { key: "seo_keywords", label: L("كلمات SEO المفتاحية", "SEO keywords"), kind: "multiselect" },
    { key: "og_image_url", label: L("رابط صورة OG", "OG image URL"), kind: "text" },
  ],
  listColumns: [
    { key: "title_en", label: L("العنوان", "Title"), sortable: true },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "workflow_state", label: L("الحالة", "State"), render: "workflow" },
    { key: "sort_order", label: L("الترتيب", "Order"), sortable: true },
    { key: "updated_at", label: L("آخر تحديث", "Updated"), render: "date", sortable: true },
  ],
});
