import { registerEntity } from "@/admin/lib/entity-registry";

registerEntity({
  key: "service",
  label: "Service",
  labelPlural: "Services",
  table: "services",
  slugColumn: "slug",
  hasI18n: true,
  supportsWorkflow: true,
  supportsVersioning: true,
  deletable: true,
  section: "content",
  icon: "Sparkles",
  fields: [
    { key: "slug", label: "Slug", kind: "slug", required: true },
    { key: "title_ar", label: "Title (AR)", kind: "text", required: true, localized: true },
    { key: "title_en", label: "Title (EN)", kind: "text", required: true, localized: true },
    { key: "description_ar", label: "Description (AR)", kind: "textarea", localized: true },
    { key: "description_en", label: "Description (EN)", kind: "textarea", localized: true },
    { key: "features", label: "Features", kind: "json", helpText: "Array of strings — one feature per entry." },
    { key: "icon", label: "Icon (Lucide name)", kind: "text" },
    { key: "cta_label_ar", label: "CTA label (AR)", kind: "text", localized: true },
    { key: "cta_label_en", label: "CTA label (EN)", kind: "text", localized: true },
    { key: "cta_href", label: "CTA href", kind: "text" },
    { key: "featured", label: "Featured", kind: "boolean" },
    { key: "sort_order", label: "Sort order", kind: "number" },
    { key: "seo_title_ar", label: "SEO title (AR)", kind: "text", localized: true },
    { key: "seo_title_en", label: "SEO title (EN)", kind: "text", localized: true },
    { key: "seo_description_ar", label: "SEO description (AR)", kind: "textarea", localized: true },
    { key: "seo_description_en", label: "SEO description (EN)", kind: "textarea", localized: true },
    { key: "seo_keywords", label: "SEO keywords", kind: "multiselect" },
    { key: "og_image_url", label: "OG image URL", kind: "text" },
  ],
  listColumns: [
    { key: "title_en", label: "Title", sortable: true },
    { key: "slug", label: "Slug" },
    { key: "workflow_state", label: "State", render: "workflow" },
    { key: "sort_order", label: "Order", sortable: true },
    { key: "updated_at", label: "Updated", render: "date", sortable: true },
  ],
});
