/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GoSplatRouteImport } from './routes/go.$'
import { Route as EnRssDotxmlRouteImport } from './routes/en.rss[.]xml'
import { Route as EnPackagesRouteImport } from './routes/en.packages'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ProjectsCategoryIndexRouteImport } from './routes/projects.$category.index'
import { Route as InsightsCategoryIndexRouteImport } from './routes/insights.$category.index'
import { Route as EnProjectsIndexRouteImport } from './routes/en.projects.index'
import { Route as EnInsightsIndexRouteImport } from './routes/en.insights.index'
import { Route as AdminInsightsIndexRouteImport } from './routes/admin.insights.index'
import { Route as ProjectsCategorySlugRouteImport } from './routes/projects.$category.$slug'
import { Route as InsightsCategorySlugRouteImport } from './routes/insights.$category.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AdminInsightsNewRouteImport } from './routes/admin.insights.new'
import { Route as AdminInsightsIdRouteImport } from './routes/admin.insights.$id'
import { Route as EnProjectsCategoryIndexRouteImport } from './routes/en.projects.$category.index'
import { Route as EnInsightsCategoryIndexRouteImport } from './routes/en.insights.$category.index'
import { Route as EnProjectsCategorySlugRouteImport } from './routes/en.projects.$category.$slug'
import { Route as EnInsightsCategorySlugRouteImport } from './routes/en.insights.$category.$slug'
import { Route as ApiPublicInsightsCoverSplatRouteImport } from './routes/api/public/insights.cover.$'

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GoSplatRoute = GoSplatRouteImport.update({
  id: '/go/$',
  path: '/go/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRssDotxmlRoute = EnRssDotxmlRouteImport.update({
  id: '/en/rss.xml',
  path: '/en/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPackagesRoute = EnPackagesRouteImport.update({
  id: '/en/packages',
  path: '/en/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsCategoryIndexRoute = ProjectsCategoryIndexRouteImport.update({
  id: '/projects/$category/',
  path: '/projects/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsCategoryIndexRoute = InsightsCategoryIndexRouteImport.update({
  id: '/insights/$category/',
  path: '/insights/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsIndexRoute = EnProjectsIndexRouteImport.update({
  id: '/en/projects/',
  path: '/en/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInsightsIndexRoute = EnInsightsIndexRouteImport.update({
  id: '/en/insights/',
  path: '/en/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsIndexRoute = AdminInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsCategorySlugRoute = ProjectsCategorySlugRouteImport.update({
  id: '/projects/$category/$slug',
  path: '/projects/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsCategorySlugRoute = InsightsCategorySlugRouteImport.update({
  id: '/insights/$category/$slug',
  path: '/insights/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsNewRoute = AdminInsightsNewRouteImport.update({
  id: '/insights/new',
  path: '/insights/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsIdRoute = AdminInsightsIdRouteImport.update({
  id: '/insights/$id',
  path: '/insights/$id',
  getParentRoute: () => AdminRoute,
} as any)
const EnProjectsCategoryIndexRoute = EnProjectsCategoryIndexRouteImport.update({
  id: '/en/projects/$category/',
  path: '/en/projects/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInsightsCategoryIndexRoute = EnInsightsCategoryIndexRouteImport.update({
  id: '/en/insights/$category/',
  path: '/en/insights/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsCategorySlugRoute = EnProjectsCategorySlugRouteImport.update({
  id: '/en/projects/$category/$slug',
  path: '/en/projects/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInsightsCategorySlugRoute = EnInsightsCategorySlugRouteImport.update({
  id: '/en/insights/$category/$slug',
  path: '/en/insights/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInsightsCoverSplatRoute =
  ApiPublicInsightsCoverSplatRouteImport.update({
    id: '/api/public/insights/cover/$',
    path: '/api/public/insights/cover/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/en/rss.xml': typeof EnRssDotxmlRoute
  '/go/$': typeof GoSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/insights/$id': typeof AdminInsightsIdRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/insights/$category/$slug': typeof InsightsCategorySlugRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/en/insights/': typeof EnInsightsIndexRoute
  '/en/projects/': typeof EnProjectsIndexRoute
  '/insights/$category/': typeof InsightsCategoryIndexRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
  '/en/insights/$category/$slug': typeof EnInsightsCategorySlugRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/insights/$category/': typeof EnInsightsCategoryIndexRoute
  '/en/projects/$category/': typeof EnProjectsCategoryIndexRoute
  '/api/public/insights/cover/$': typeof ApiPublicInsightsCoverSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/en/rss.xml': typeof EnRssDotxmlRoute
  '/go/$': typeof GoSplatRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/insights/$id': typeof AdminInsightsIdRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/insights/$category/$slug': typeof InsightsCategorySlugRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/insights': typeof AdminInsightsIndexRoute
  '/en/insights': typeof EnInsightsIndexRoute
  '/en/projects': typeof EnProjectsIndexRoute
  '/insights/$category': typeof InsightsCategoryIndexRoute
  '/projects/$category': typeof ProjectsCategoryIndexRoute
  '/en/insights/$category/$slug': typeof EnInsightsCategorySlugRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/insights/$category': typeof EnInsightsCategoryIndexRoute
  '/en/projects/$category': typeof EnProjectsCategoryIndexRoute
  '/api/public/insights/cover/$': typeof ApiPublicInsightsCoverSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/en/rss.xml': typeof EnRssDotxmlRoute
  '/go/$': typeof GoSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/insights/$id': typeof AdminInsightsIdRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/insights/$category/$slug': typeof InsightsCategorySlugRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/en/insights/': typeof EnInsightsIndexRoute
  '/en/projects/': typeof EnProjectsIndexRoute
  '/insights/$category/': typeof InsightsCategoryIndexRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
  '/en/insights/$category/$slug': typeof EnInsightsCategorySlugRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/insights/$category/': typeof EnInsightsCategoryIndexRoute
  '/en/projects/$category/': typeof EnProjectsCategoryIndexRoute
  '/api/public/insights/cover/$': typeof ApiPublicInsightsCoverSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/packages'
    | '/rss.xml'
    | '/admin/audit'
    | '/en/contact'
    | '/en/packages'
    | '/en/rss.xml'
    | '/go/$'
    | '/admin/'
    | '/en/'
    | '/insights/'
    | '/projects/'
    | '/admin/insights/$id'
    | '/admin/insights/new'
    | '/api/public/contact'
    | '/insights/$category/$slug'
    | '/projects/$category/$slug'
    | '/admin/insights/'
    | '/en/insights/'
    | '/en/projects/'
    | '/insights/$category/'
    | '/projects/$category/'
    | '/en/insights/$category/$slug'
    | '/en/projects/$category/$slug'
    | '/en/insights/$category/'
    | '/en/projects/$category/'
    | '/api/public/insights/cover/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/packages'
    | '/rss.xml'
    | '/admin/audit'
    | '/en/contact'
    | '/en/packages'
    | '/en/rss.xml'
    | '/go/$'
    | '/admin'
    | '/en'
    | '/insights'
    | '/projects'
    | '/admin/insights/$id'
    | '/admin/insights/new'
    | '/api/public/contact'
    | '/insights/$category/$slug'
    | '/projects/$category/$slug'
    | '/admin/insights'
    | '/en/insights'
    | '/en/projects'
    | '/insights/$category'
    | '/projects/$category'
    | '/en/insights/$category/$slug'
    | '/en/projects/$category/$slug'
    | '/en/insights/$category'
    | '/en/projects/$category'
    | '/api/public/insights/cover/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/packages'
    | '/rss.xml'
    | '/admin/audit'
    | '/en/contact'
    | '/en/packages'
    | '/en/rss.xml'
    | '/go/$'
    | '/admin/'
    | '/en/'
    | '/insights/'
    | '/projects/'
    | '/admin/insights/$id'
    | '/admin/insights/new'
    | '/api/public/contact'
    | '/insights/$category/$slug'
    | '/projects/$category/$slug'
    | '/admin/insights/'
    | '/en/insights/'
    | '/en/projects/'
    | '/insights/$category/'
    | '/projects/$category/'
    | '/en/insights/$category/$slug'
    | '/en/projects/$category/$slug'
    | '/en/insights/$category/'
    | '/en/projects/$category/'
    | '/api/public/insights/cover/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  EnContactRoute: typeof EnContactRoute
  EnPackagesRoute: typeof EnPackagesRoute
  EnRssDotxmlRoute: typeof EnRssDotxmlRoute
  GoSplatRoute: typeof GoSplatRoute
  EnIndexRoute: typeof EnIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  InsightsCategorySlugRoute: typeof InsightsCategorySlugRoute
  ProjectsCategorySlugRoute: typeof ProjectsCategorySlugRoute
  EnInsightsIndexRoute: typeof EnInsightsIndexRoute
  EnProjectsIndexRoute: typeof EnProjectsIndexRoute
  InsightsCategoryIndexRoute: typeof InsightsCategoryIndexRoute
  ProjectsCategoryIndexRoute: typeof ProjectsCategoryIndexRoute
  EnInsightsCategorySlugRoute: typeof EnInsightsCategorySlugRoute
  EnProjectsCategorySlugRoute: typeof EnProjectsCategorySlugRoute
  EnInsightsCategoryIndexRoute: typeof EnInsightsCategoryIndexRoute
  EnProjectsCategoryIndexRoute: typeof EnProjectsCategoryIndexRoute
  ApiPublicInsightsCoverSplatRoute: typeof ApiPublicInsightsCoverSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/go/$': {
      id: '/go/$'
      path: '/go/$'
      fullPath: '/go/$'
      preLoaderRoute: typeof GoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/rss.xml': {
      id: '/en/rss.xml'
      path: '/en/rss.xml'
      fullPath: '/en/rss.xml'
      preLoaderRoute: typeof EnRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/packages': {
      id: '/en/packages'
      path: '/en/packages'
      fullPath: '/en/packages'
      preLoaderRoute: typeof EnPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$category/': {
      id: '/projects/$category/'
      path: '/projects/$category'
      fullPath: '/projects/$category/'
      preLoaderRoute: typeof ProjectsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$category/': {
      id: '/insights/$category/'
      path: '/insights/$category'
      fullPath: '/insights/$category/'
      preLoaderRoute: typeof InsightsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/': {
      id: '/en/projects/'
      path: '/en/projects'
      fullPath: '/en/projects/'
      preLoaderRoute: typeof EnProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/insights/': {
      id: '/en/insights/'
      path: '/en/insights'
      fullPath: '/en/insights/'
      preLoaderRoute: typeof EnInsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights/': {
      id: '/admin/insights/'
      path: '/insights'
      fullPath: '/admin/insights/'
      preLoaderRoute: typeof AdminInsightsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$category/$slug': {
      id: '/projects/$category/$slug'
      path: '/projects/$category/$slug'
      fullPath: '/projects/$category/$slug'
      preLoaderRoute: typeof ProjectsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$category/$slug': {
      id: '/insights/$category/$slug'
      path: '/insights/$category/$slug'
      fullPath: '/insights/$category/$slug'
      preLoaderRoute: typeof InsightsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights/new': {
      id: '/admin/insights/new'
      path: '/insights/new'
      fullPath: '/admin/insights/new'
      preLoaderRoute: typeof AdminInsightsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/$id': {
      id: '/admin/insights/$id'
      path: '/insights/$id'
      fullPath: '/admin/insights/$id'
      preLoaderRoute: typeof AdminInsightsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/projects/$category/': {
      id: '/en/projects/$category/'
      path: '/en/projects/$category'
      fullPath: '/en/projects/$category/'
      preLoaderRoute: typeof EnProjectsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/insights/$category/': {
      id: '/en/insights/$category/'
      path: '/en/insights/$category'
      fullPath: '/en/insights/$category/'
      preLoaderRoute: typeof EnInsightsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/$category/$slug': {
      id: '/en/projects/$category/$slug'
      path: '/en/projects/$category/$slug'
      fullPath: '/en/projects/$category/$slug'
      preLoaderRoute: typeof EnProjectsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/insights/$category/$slug': {
      id: '/en/insights/$category/$slug'
      path: '/en/insights/$category/$slug'
      fullPath: '/en/insights/$category/$slug'
      preLoaderRoute: typeof EnInsightsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insights/cover/$': {
      id: '/api/public/insights/cover/$'
      path: '/api/public/insights/cover/$'
      fullPath: '/api/public/insights/cover/$'
      preLoaderRoute: typeof ApiPublicInsightsCoverSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInsightsIdRoute: typeof AdminInsightsIdRoute
  AdminInsightsNewRoute: typeof AdminInsightsNewRoute
  AdminInsightsIndexRoute: typeof AdminInsightsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInsightsIdRoute: AdminInsightsIdRoute,
  AdminInsightsNewRoute: AdminInsightsNewRoute,
  AdminInsightsIndexRoute: AdminInsightsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  EnContactRoute: EnContactRoute,
  EnPackagesRoute: EnPackagesRoute,
  EnRssDotxmlRoute: EnRssDotxmlRoute,
  GoSplatRoute: GoSplatRoute,
  EnIndexRoute: EnIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  InsightsCategorySlugRoute: InsightsCategorySlugRoute,
  ProjectsCategorySlugRoute: ProjectsCategorySlugRoute,
  EnInsightsIndexRoute: EnInsightsIndexRoute,
  EnProjectsIndexRoute: EnProjectsIndexRoute,
  InsightsCategoryIndexRoute: InsightsCategoryIndexRoute,
  ProjectsCategoryIndexRoute: ProjectsCategoryIndexRoute,
  EnInsightsCategorySlugRoute: EnInsightsCategorySlugRoute,
  EnProjectsCategorySlugRoute: EnProjectsCategorySlugRoute,
  EnInsightsCategoryIndexRoute: EnInsightsCategoryIndexRoute,
  EnProjectsCategoryIndexRoute: EnProjectsCategoryIndexRoute,
  ApiPublicInsightsCoverSplatRoute: ApiPublicInsightsCoverSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
