/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as GoSplatRouteImport } from './routes/go.$'
import { Route as EnPackagesRouteImport } from './routes/en.packages'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as ProjectsCategoryIndexRouteImport } from './routes/projects.$category.index'
import { Route as EnProjectsIndexRouteImport } from './routes/en.projects.index'
import { Route as ProjectsCategorySlugRouteImport } from './routes/projects.$category.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as EnProjectsCategoryIndexRouteImport } from './routes/en.projects.$category.index'
import { Route as EnProjectsCategorySlugRouteImport } from './routes/en.projects.$category.$slug'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSplatRoute = GoSplatRouteImport.update({
  id: '/go/$',
  path: '/go/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPackagesRoute = EnPackagesRouteImport.update({
  id: '/en/packages',
  path: '/en/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCategoryIndexRoute = ProjectsCategoryIndexRouteImport.update({
  id: '/projects/$category/',
  path: '/projects/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsIndexRoute = EnProjectsIndexRouteImport.update({
  id: '/en/projects/',
  path: '/en/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCategorySlugRoute = ProjectsCategorySlugRouteImport.update({
  id: '/projects/$category/$slug',
  path: '/projects/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsCategoryIndexRoute = EnProjectsCategoryIndexRouteImport.update({
  id: '/en/projects/$category/',
  path: '/en/projects/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsCategorySlugRoute = EnProjectsCategorySlugRouteImport.update({
  id: '/en/projects/$category/$slug',
  path: '/en/projects/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/go/$': typeof GoSplatRoute
  '/en/': typeof EnIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/projects/$category/': typeof EnProjectsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/go/$': typeof GoSplatRoute
  '/en': typeof EnIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/en/projects': typeof EnProjectsIndexRoute
  '/projects/$category': typeof ProjectsCategoryIndexRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/projects/$category': typeof EnProjectsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/en/contact': typeof EnContactRoute
  '/en/packages': typeof EnPackagesRoute
  '/go/$': typeof GoSplatRoute
  '/en/': typeof EnIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
  '/en/projects/$category/$slug': typeof EnProjectsCategorySlugRoute
  '/en/projects/$category/': typeof EnProjectsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/packages'
    | '/en/contact'
    | '/en/packages'
    | '/go/$'
    | '/en/'
    | '/projects/'
    | '/api/public/contact'
    | '/projects/$category/$slug'
    | '/en/projects/'
    | '/projects/$category/'
    | '/en/projects/$category/$slug'
    | '/en/projects/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/packages'
    | '/en/contact'
    | '/en/packages'
    | '/go/$'
    | '/en'
    | '/projects'
    | '/api/public/contact'
    | '/projects/$category/$slug'
    | '/en/projects'
    | '/projects/$category'
    | '/en/projects/$category/$slug'
    | '/en/projects/$category'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/packages'
    | '/en/contact'
    | '/en/packages'
    | '/go/$'
    | '/en/'
    | '/projects/'
    | '/api/public/contact'
    | '/projects/$category/$slug'
    | '/en/projects/'
    | '/projects/$category/'
    | '/en/projects/$category/$slug'
    | '/en/projects/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  EnContactRoute: typeof EnContactRoute
  EnPackagesRoute: typeof EnPackagesRoute
  GoSplatRoute: typeof GoSplatRoute
  EnIndexRoute: typeof EnIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ProjectsCategorySlugRoute: typeof ProjectsCategorySlugRoute
  EnProjectsIndexRoute: typeof EnProjectsIndexRoute
  ProjectsCategoryIndexRoute: typeof ProjectsCategoryIndexRoute
  EnProjectsCategorySlugRoute: typeof EnProjectsCategorySlugRoute
  EnProjectsCategoryIndexRoute: typeof EnProjectsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$': {
      id: '/go/$'
      path: '/go/$'
      fullPath: '/go/$'
      preLoaderRoute: typeof GoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/packages': {
      id: '/en/packages'
      path: '/en/packages'
      fullPath: '/en/packages'
      preLoaderRoute: typeof EnPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$category/': {
      id: '/projects/$category/'
      path: '/projects/$category'
      fullPath: '/projects/$category/'
      preLoaderRoute: typeof ProjectsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/': {
      id: '/en/projects/'
      path: '/en/projects'
      fullPath: '/en/projects/'
      preLoaderRoute: typeof EnProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$category/$slug': {
      id: '/projects/$category/$slug'
      path: '/projects/$category/$slug'
      fullPath: '/projects/$category/$slug'
      preLoaderRoute: typeof ProjectsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/$category/': {
      id: '/en/projects/$category/'
      path: '/en/projects/$category'
      fullPath: '/en/projects/$category/'
      preLoaderRoute: typeof EnProjectsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/$category/$slug': {
      id: '/en/projects/$category/$slug'
      path: '/en/projects/$category/$slug'
      fullPath: '/en/projects/$category/$slug'
      preLoaderRoute: typeof EnProjectsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  EnContactRoute: EnContactRoute,
  EnPackagesRoute: EnPackagesRoute,
  GoSplatRoute: GoSplatRoute,
  EnIndexRoute: EnIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ProjectsCategorySlugRoute: ProjectsCategorySlugRoute,
  EnProjectsIndexRoute: EnProjectsIndexRoute,
  ProjectsCategoryIndexRoute: ProjectsCategoryIndexRoute,
  EnProjectsCategorySlugRoute: EnProjectsCategorySlugRoute,
  EnProjectsCategoryIndexRoute: EnProjectsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
